# Generated by Django 3.0.6 on 2020-09-21 16:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0002_trainer_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(default='', verbose_name='Краткое описание группы')),
                ('days', models.CharField(choices=[('1,3,5', 'Вторник/Четверг'), ('2,4,5', 'Понедельник/Среда')], default='none', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(default='Dad', max_length=50, verbose_name='ФИО')),
                ('phone1', models.CharField(default=0, max_length=11)),
                ('name2', models.CharField(default='Mom', max_length=50, verbose_name='ФИО')),
                ('phone2', models.CharField(default=0, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Kids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('birthday', models.DateField(default=django.utils.timezone.now)),
                ('sportCategory', models.CharField(choices=[('КМС', 'КМС'), ('МС', 'МС'), ('1-спортивный', '1-спортивный'), ('2-спортивный', '2-спортивный'), ('3-спортивный', '3-спортивный'), ('1-юношеский', '1-юношеский'), ('2-юношеский', '2-юношеский'), ('3-юношеский', '3-юношеский'), ('Юный фигурист', 'Юный фигурист')], default='Юный фигурист', max_length=30, verbose_name='Разряд')),
                ('photo', models.ImageField(null=True, upload_to='photo')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kids.Groups')),
                ('parents', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kids.Parents')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Trainer')),
            ],
        ),
    ]
