# Generated by Django 3.0.6 on 2020-05-20 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kids',
            name='Birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
