# Generated by Django 3.0.6 on 2020-05-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0002_kids_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parents',
            old_name='nid',
            new_name='kid',
        ),
    ]
