# Generated by Django 3.0.6 on 2020-05-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0003_auto_20200526_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='kid',
        ),
        migrations.AddField(
            model_name='parents',
            name='child',
            field=models.ManyToManyField(to='kids.Kids'),
        ),
    ]
