# Generated by Django 3.0.6 on 2020-05-28 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0004_auto_20200528_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='child',
        ),
        migrations.AddField(
            model_name='parents',
            name='kid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kids.Kids'),
        ),
    ]
