# Generated by Django 3.0.6 on 2020-05-28 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0005_auto_20200528_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='kid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kids.Kids'),
        ),
    ]
