# Generated by Django 3.0.6 on 2020-05-28 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0006_auto_20200528_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='kid',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='name',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='phone',
        ),
        migrations.AddField(
            model_name='kids',
            name='parents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kids.Parents'),
        ),
        migrations.AddField(
            model_name='parents',
            name='name1',
            field=models.CharField(default='Dad', max_length=50, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='parents',
            name='name2',
            field=models.CharField(default='Mom', max_length=50, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='parents',
            name='phone1',
            field=models.CharField(default=0, max_length=11),
        ),
        migrations.AddField(
            model_name='parents',
            name='phone2',
            field=models.CharField(default=0, max_length=11),
        ),
    ]
