# Generated by Django 3.0.6 on 2020-05-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0007_auto_20200528_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='kids',
            name='status',
            field=models.CharField(choices=[('CMS', 'Кандидат'), ('MS', 'On loan'), ('S1', 'Available'), ('S2', 'Reserved'), ('S3', 'Maintenance'), ('Y1', 'On loan'), ('Y2', 'Available'), ('Y3', 'Reserved'), ('YF', 'Maintenance')], default='YF', help_text='Book availability', max_length=3),
        ),
    ]
