# Generated by Django 3.0.6 on 2020-05-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0009_auto_20200531_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kids',
            name='category',
        ),
        migrations.AlterField(
            model_name='kids',
            name='sportCategory',
            field=models.CharField(choices=[('CMS', 'КМС'), ('MS', 'МС'), ('S1', '1-спортивный'), ('S2', '2-спортивный'), ('S3', '3-спортивный'), ('Y1', '1-юношеский'), ('Y2', '2-юношеский'), ('Y3', '3-юношеский'), ('YF', 'Юный фигурист')], default='YF', max_length=3, verbose_name='Разряд'),
        ),
        migrations.DeleteModel(
            name='SportsCategories',
        ),
    ]
