# Generated by Django 3.0.6 on 2020-06-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0011_auto_20200608_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='kids',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
