# Generated by Django 3.0.6 on 2020-06-09 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0012_kids_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kids',
            name='photo',
        ),
    ]
