# Generated by Django 3.0.6 on 2020-06-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0014_kids_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kids',
            name='photo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
