# Generated by Django 3.0.6 on 2020-06-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название товара')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('photo', models.ImageField(null=True, upload_to='products')),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('разное', 'разное'), ('ботинки', 'Ботинки'), ('лезвия', 'Лезвия'), ('костюм', 'костюм')], default='разное', max_length=20, verbose_name='Тип товара')),
            ],
        ),
    ]
