# Generated by Django 3.0.6 on 2020-06-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='characteristics',
            field=models.TextField(default='none', verbose_name='Характеристики товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(verbose_name='Краткое описание товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('разное', 'Разное'), ('ботинки', 'Ботинки'), ('лезвия', 'Лезвия'), ('костюм', 'Костюм')], default='разное', max_length=20, verbose_name='Тип товара'),
        ),
    ]
